/* Generated By:JavaCC: Do not edit this line. DeploymentViewParserTreeConstants.java Version 6.0_1 */
package wyvern.tools.parsing.coreparser.arch.views.deployment;

public interface DeploymentViewParserTreeConstants
{
  public int JJTDEPLOYMENTDECL = 0;
  public int JJTVOID = 1;
  public int JJTSETTER = 2;
  public int JJTLHS = 3;
  public int JJTIDENTIFIER = 4;
  public int JJTLHSREMAINING = 5;
  public int JJTSTRINGLITERAL = 6;


  public String[] jjtNodeName = {
    "DeploymentDecl",
    "void",
    "Setter",
    "Lhs",
    "Identifier",
    "LhsRemaining",
    "StringLiteral",
  };
}
/* JavaCC - OriginalChecksum=e1028fb63cb59453bbd921f6c5217ac3 (do not edit this line) */
