/* Generated By:JJTree&JavaCC: Do not edit this line. DeploymentViewParserConstants.java */
package wyvern.tools.parsing.coreparser.arch.views.deployment;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface DeploymentViewParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int DEPLOYMENT = 1;
  /** RegularExpression Id. */
  int EXTENDS = 2;
  /** RegularExpression Id. */
  int SINGLE_LINE_COMMENT = 3;
  /** RegularExpression Id. */
  int MULTI_LINE_COMMENT = 4;
  /** RegularExpression Id. */
  int WHITESPACE = 5;
  /** RegularExpression Id. */
  int DEDENT = 6;
  /** RegularExpression Id. */
  int INDENT = 7;
  /** RegularExpression Id. */
  int NEWLINE = 8;
  /** RegularExpression Id. */
  int IDENTIFIER = 9;
  /** RegularExpression Id. */
  int DOT = 10;
  /** RegularExpression Id. */
  int EQUALS = 11;
  /** RegularExpression Id. */
  int STRING_LITERAL = 12;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"deployment\"",
    "\"extends\"",
    "<SINGLE_LINE_COMMENT>",
    "<MULTI_LINE_COMMENT>",
    "<WHITESPACE>",
    "<DEDENT>",
    "<INDENT>",
    "<NEWLINE>",
    "<IDENTIFIER>",
    "<DOT>",
    "<EQUALS>",
    "<STRING_LITERAL>",
  };

}
