/* Generated By:JavaCC: Do not edit this line. TokenManager.java Version 6.0 */
/* JavaCCOptions:SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package wyvern.tools.parsing.coreparser.arch.views.deployment;

/**
 * An implementation for this interface is generated by
 * JavaCCParser.  The user is free to use any implementation
 * of their choice.
 */

public interface TokenManager {

  /** This gets the next token from the input stream.
   *  A token of kind 0 (<EOF>) should be returned on EOF.
   */
  public Token getNextToken();

}
/* JavaCC - OriginalChecksum=ef2deb6142d3b5ae6e5249f57678ffcf (do not edit this line) */
