/* Generated By:JavaCC: Do not edit this line. ArchParserTreeConstants.java Version 6.0_1 */
package wyvern.tools.parsing.coreparser.arch;

public interface ArchParserTreeConstants
{
  public int JJTARCHDESC = 0;
  public int JJTVOID = 1;
  public int JJTCOMPONENTTYPEDECL = 2;
  public int JJTCONNECTORTYPEDECL = 3;
  public int JJTARCHITECTURETYPEDECL = 4;
  public int JJTCOMPONENTDECL = 5;
  public int JJTCONNECTORDECL = 6;
  public int JJTATTACHMENTDECL = 7;
  public int JJTBINDINGDECL = 8;
  public int JJTENTRYPOINTDECL = 9;
  public int JJTPORTDECL = 10;
  public int JJTVALDECL = 11;


  public String[] jjtNodeName = {
    "ArchDesc",
    "void",
    "ComponentTypeDecl",
    "ConnectorTypeDecl",
    "ArchitectureTypeDecl",
    "ComponentDecl",
    "ConnectorDecl",
    "AttachmentDecl",
    "BindingDecl",
    "EntryPointDecl",
    "PortDecl",
    "ValDecl",
  };
}
/* JavaCC - OriginalChecksum=d96483c0848943d4568a4a2e2559f9f6 (do not edit this line) */
